/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Subject = IDL.Variant({
  'math' : IDL.Null,
  'history' : IDL.Null,
  'literature' : IDL.Null,
  'science' : IDL.Null,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'subject' : Subject,
  'answer' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StudyProgress = IDL.Record({
  'messages' : IDL.Vec(IDL.Nat),
  'questionsAsked' : IDL.Nat,
  'subjectsVisited' : IDL.Vec(Subject),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'askQuestion' : IDL.Func([IDL.Text, Subject], [Message], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getCallerStudyProgress' : IDL.Func([], [StudyProgress], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessage' : IDL.Func([IDL.Nat], [IDL.Opt(Message)], ['query']),
  'getMessagesByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMostPopularSubject' : IDL.Func([], [IDL.Opt(Subject)], ['query']),
  'getMostStudiousUser' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getStudyProgress' : IDL.Func([IDL.Principal], [StudyProgress], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordStudySession' : IDL.Func([Subject, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Subject = IDL.Variant({
    'math' : IDL.Null,
    'history' : IDL.Null,
    'literature' : IDL.Null,
    'science' : IDL.Null,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'subject' : Subject,
    'answer' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StudyProgress = IDL.Record({
    'messages' : IDL.Vec(IDL.Nat),
    'questionsAsked' : IDL.Nat,
    'subjectsVisited' : IDL.Vec(Subject),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'askQuestion' : IDL.Func([IDL.Text, Subject], [Message], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getCallerStudyProgress' : IDL.Func([], [StudyProgress], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessage' : IDL.Func([IDL.Nat], [IDL.Opt(Message)], ['query']),
    'getMessagesByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMostPopularSubject' : IDL.Func([], [IDL.Opt(Subject)], ['query']),
    'getMostStudiousUser' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getStudyProgress' : IDL.Func([IDL.Principal], [StudyProgress], ['query']),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordStudySession' : IDL.Func([Subject, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };