/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'id' : bigint,
  'question' : string,
  'subject' : Subject,
  'answer' : string,
  'sender' : Principal,
  'timestamp' : Time,
}
export interface StudyProgress {
  'messages' : Array<bigint>,
  'questionsAsked' : bigint,
  'subjectsVisited' : Array<Subject>,
}
export type Subject = { 'math' : null } |
  { 'history' : null } |
  { 'literature' : null } |
  { 'science' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'askQuestion' : ActorMethod<[string, Subject], Message>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getCallerStudyProgress' : ActorMethod<[], StudyProgress>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessage' : ActorMethod<[bigint], [] | [Message]>,
  'getMessagesByUser' : ActorMethod<[Principal], Array<Message>>,
  /**
   * / Get subject with most questions asked
   */
  'getMostPopularSubject' : ActorMethod<[], [] | [Subject]>,
  /**
   * / Calculate user with most questions asked
   */
  'getMostStudiousUser' : ActorMethod<[], [] | [Principal]>,
  'getStudyProgress' : ActorMethod<[Principal], StudyProgress>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordStudySession' : ActorMethod<[Subject, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];